### ISSUE TITLE
Demo #demo3 is broken

### ISSUE THREAD

**Issue by Rinzwind** [pharo-graphics/Toplo#193] opened 2024-08-30 14:31 UTC
In the ‘dev’ branch, specifically commit 17adaae11c4ebc3b, #demo3 on ToploDemoPresenter is broken:

<p align="center">
<img width="350" src="https://github.com/user-attachments/assets/994ac8dc-ba02-4427-a44e-a6c6dd44dfb4">
</p>

In the ‘Pharo12’ branch, specifically commit f9e59b91fc0aeba2, it works:

<p align="center">
<img width="350" src="https://github.com/user-attachments/assets/3c37fded-165c-4912-8faf-f5e2e8cda1ab">
</p>

I’m not sure what changed.

**Comment by plantec** [comment] 2024-09-10 07:30
thanks, this highlights a regression. 
The space root was not able to manage skin anymore (since it is a regular BlElement and not a ToElement, it is not able to manage skin by default). 
Fixed by sending #ensureCanManageSkin in BlSpace>>toTheme:

**Closed by plantec** 2024-09-10 07:30 UTC
